CREATE TABLE publishers (
  id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(200) NOT NULL,
  CONSTRAINT uq_publishers_name UNIQUE (name)
);

CREATE TABLE authors (
  id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(200) NOT NULL,
  CONSTRAINT uq_authors_name UNIQUE (name)
);

CREATE TABLE books (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        VARCHAR2(300) NOT NULL,
  author_id    NUMBER NOT NULL,
  publisher_id NUMBER NOT NULL,
  CONSTRAINT fk_books_author    FOREIGN KEY (author_id)    REFERENCES authors (id),
  CONSTRAINT fk_books_publisher FOREIGN KEY (publisher_id) REFERENCES publishers (id)
);

CREATE INDEX ix_books_author_id    ON books (author_id);
CREATE INDEX ix_books_publisher_id ON books (publisher_id);

CREATE TABLE audit_logs (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name VARCHAR2(30)  NOT NULL,
  action     VARCHAR2(20)  NOT NULL,
  record_id  NUMBER,
  changed_by VARCHAR2(128) NOT NULL,
  changed_at TIMESTAMP     NOT NULL
);

CREATE OR REPLACE TYPE book_detail_obj AS OBJECT (
  book_id        NUMBER,
  title          VARCHAR2(300),
  author_name    VARCHAR2(200),
  publisher_name VARCHAR2(200)
);

CREATE OR REPLACE TYPE book_detail_tab AS TABLE OF book_detail_obj;
