BEGIN
  FOR obj IN (
    SELECT 'BOOKS'      AS name, 'TABLE' AS type FROM dual UNION ALL
    SELECT 'AUTHORS',      'TABLE' FROM dual UNION ALL
    SELECT 'PUBLISHERS',   'TABLE' FROM dual
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE ' || obj.name || ' CASCADE CONSTRAINTS';
    EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
    END;
  END LOOP;
END;
/

CREATE TABLE publishers (
  publisher_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR2(200)  NOT NULL,
  country        VARCHAR2(100),
  created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_publishers_name UNIQUE (name)
);

CREATE TABLE authors (
  author_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name     VARCHAR2(100)  NOT NULL,
  last_name      VARCHAR2(100)  NOT NULL,
  birth_year     NUMBER(4),
  created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_authors_full_name UNIQUE (first_name, last_name),
  CONSTRAINT ck_authors_birth_year CHECK (birth_year IS NULL OR birth_year BETWEEN 1000 AND 2200)
);

CREATE TABLE books (
  book_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title              VARCHAR2(300)  NOT NULL,
  isbn               VARCHAR2(20)   NOT NULL,
  publication_year   NUMBER(4),
  author_id          NUMBER         NOT NULL,
  publisher_id       NUMBER         NOT NULL,
  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_books_isbn UNIQUE (isbn),
  CONSTRAINT fk_books_author
    FOREIGN KEY (author_id)    REFERENCES authors (author_id),
  CONSTRAINT fk_books_publisher
    FOREIGN KEY (publisher_id) REFERENCES publishers (publisher_id),
  CONSTRAINT ck_books_pub_year
    CHECK (publication_year IS NULL OR publication_year BETWEEN 1000 AND 2200)
);

CREATE INDEX ix_books_author_id    ON books (author_id);
CREATE INDEX ix_books_publisher_id ON books (publisher_id);

CREATE OR REPLACE TYPE book_detail_obj AS OBJECT (
  book_id           NUMBER,
  title             VARCHAR2(300),
  isbn              VARCHAR2(20),
  publication_year  NUMBER(4),
  author_name       VARCHAR2(200),
  publisher_name    VARCHAR2(200)
);
/

CREATE OR REPLACE TYPE book_detail_tab AS TABLE OF book_detail_obj;
/

PROMPT Schema created successfully.
